#!/usr/bin/python3
import argparse
from es2json import esgenerator
from es2json import esfatgenerator
from es2json import esidfilegenerator
from es2json import ArrayOrSingleValue
from es2json import eprint
from es2json import litter
from es2json import isint
from requests import get
from elasticsearch import Elasticsearch, helpers
import json
import sys

es=None

mapping=None

mapping={"author":{         "fields":["hasOccupation","about","workLocation","sameAs"],
                            "index":["persons","organizations","fidmove-enriched-aut"]},
         "contributor":{    "fields":["hasOccupation","about","workLocation","geo","adressRegion","sameAs"],
                            "index":["persons","organizations","fidmove-enriched-aut"]},
         "workLocation":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "location":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "mentions":{       "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "relatedEvent":{   "fields":["adressRegion","location","geo","sameAs"],
                            "index":["fidmove-enriched-aut"]}
         }

generic_mapping={"author":{ "fields":["hasOccupation","about","workLocation","sameAs","birthPlace","deathPlace"],
                            "index":["persons","organizations","fidmove-extended-aut"]},
         "contributor":{    "fields":["hasOccupation","about","workLocation","geo","adressRegion","sameAs"],
                            "index":["persons","organizations","fidmove-extended-aut"]},
         "workLocation":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "birthPlace":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "deathPlace":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "location":{   "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "mentions":{       "fields":["geo","adressRegion","sameAs"],
                            "index":["geo"]},
         "relatedEvent":{   "fields":["adressRegion","location","geo","sameAs"],
                            "index":["fidmove-extended-aut"]}
         }


def isAlive(node):
    if "deathDate" or "deathPlace" in node:
        return False
    else:
        return True

def enrich_record(node,entity,host,port,map):
    toDel=[]
    for field in mapping:
        if isinstance(node.get(field),dict):
            ret=enrich_record(node.get(field),field,host,port,map)
            if ret:
                node[field]=ret
        elif isinstance(node.get(field),list):
            for n,fld in enumerate(node.get(field)):
                ret=enrich_record(fld,field,host,port,map)
                if ret:
                    node[field][n]=ret
                else:
                    del node[field][n]
        else:
            continue
    for item in toDel:
        node.pop(item)
    if entity:
        if node.get("@id"):
            for index in mapping[entity].get("index"):
                #print(node.get("@id"))
                url="http://"+host+":"+port+"/"+index+"/schemaorg/"+node.get("@id").split("/")[-1]
                r=get(url)
                #if entity=="relatedEvent":
                    #print(r,url)
                if ( r.ok and entity!="person" ) or ( r.ok and entity=="person" and isAlive(r.json().get("_source")) ):
                    for key in mapping[entity]["fields"]:
                        if key in r.json().get("_source"):
                            node[key]=litter(node.get(key),r.json()["_source"][key])
                elif r.ok and not isAlive(r.json().get("_source")):
                    return None
        elif node.get("sameAs") and isinstance(node.get("sameAs"),str):
            search=es.search(index=",".join(mapping[entity]["index"]),doc_type="schemaorg",body={"query":{"term":{"sameAs.keyword":node.get("sameAs")}}},_source=True)
            if search.get("hits").get("total")>0:
                for response in search.get("hits").get("hits"):
                    data=response.get("_source")
                    if isAlive(data) or entity!="person":
                        for key in mapping[entity]["fields"]:
                            if data.get(key):
                                node[key]=data.get(key)
                        break
                    elif not isAlive(data) and entity=="person":
                        break
                
        elif node.get("sameAs") and isinstance(node.get("sameAs"),list):
            for sameAs in node.get("sameAs"):
                search=es.search(index=",".join(mapping[entity]["index"]),doc_type="schemaorg",body={"query":{"term":{"sameAs.keyword":sameAs}}},_source=True)
                if search.get("hits").get("total")>0:
                    for response in search.get("hits").get("hits"):
                        data=response.get("_source")
                        if isAlive(data) or entity!="person":
                            for key in mapping[entity]["fields"]:
                                if data.get(key):
                                    node[key]=data.get(key)
                            break
                        elif not isAlive(data) and entity=="person":
                            break
        else:
            pass
    return node

if __name__ == "__main__":
    #argstuff
    parser=argparse.ArgumentParser(description='Enrich Resources with authority Data for FID-Move')
    parser.add_argument('-host',type=str,help='hostname or IP-Address of the ElasticSearch-node to use. If None we try to read ldj from stdin.')
    parser.add_argument('-port',type=int,default=9200,help='Port of the ElasticSearch-node to use, default is 9200.')
    parser.add_argument('-type',type=str,help='ElasticSearch Type to use')
    parser.add_argument('-index',type=str,help='ElasticSearch Index to use')
    parser.add_argument('-id',type=str,help='map single document, given by id')
    parser.add_argument('-help',action="store_true",help="print this help")
    parser.add_argument('-stdin',action="store_true",help="If you want to read from stdin")
    parser.add_argument('-debug',action="store_true",help='Dump processed Records to stdout (mostly used for debug-purposes)')
    parser.add_argument('-server',type=str,help="use http://host:port/index/type/id?pretty syntax. overwrites host/port/index/id/pretty")
    parser.add_argument('-pretty',action="store_true",default=False,help="output tabbed json")
    parser.add_argument('-idfile',type=str,help="path to a file with IDs to process")
    parser.add_argument('-fidmove',action="store_true",default=False,help="Reduction to FIDMove")
    args=parser.parse_args()
    
    if args.server:
        slashsplit=args.server.split("/")
        args.host=slashsplit[2].rsplit(":")[0]
        if isint(args.server.split(":")[2].rsplit("/")[0]):
            args.port=args.server.split(":")[2].split("/")[0]
        if len(slashsplit)>3:
            args.index=args.server.split("/")[3]
        if len(slashsplit)>4:
            args.type=slashsplit[4]
        if len(slashsplit)>5:
            if "?pretty" in args.server:
                args.pretty=True
                args.id=slashsplit[5].rsplit("?")[0]
            else:
                args.id=slashsplit[5]
    if args.help:
        parser.print_help(sys.stderr)
        exit()
    if args.pretty:
        tabbing=4
    else:
        tabbing=None
    es=Elasticsearch([{'host':args.host}],port=args.port)
    map=None
    if args.fidmove:
        map=mapping
    else:
        map=generic_mapping

    if args.stdin:
        for line in sys.stdin:
            newrecord=enrich_record(json.loads(line),None,args.host,str(args.port),map)
            if newrecord.get("author") or newrecord.get("contributor"):
                print(json.dumps(enrich_record(newrecord,None,args.host,str(args.port)),indent=tabbing),map)
    elif args.idfile:
        for record in esidfilegenerator(host=args.host,port=9200,index=args.index,type=args.type,body=None,source=True,source_exclude=None,source_include=None,headless=True,idfile=args.idfile):
            #recstrlen=len(json.dumps(record,indent=None))
            #print(json.dumps(record,indent=tabbing),"\n")
            length=len(json.dumps(record,indent=None))
            newrecord=enrich_record(record,None,args.host,str(args.port),map)
            dumpstring=str(json.dumps(newrecord,indent=None))
            if len(dumpstring) > length:
            #if newrecord.get("author") or newrecord.get("contributor"):
                print(json.dumps(newrecord,indent=tabbing))
    
    else:
        if args.fidmove and args.index=="resources":
           searchbody={
  "query": {
    "bool" : {
      "must": [{
        "bool": {
          "minimum_should_match": 1,
          "should": [
            {"match": {"inLanguage.keyword": "ger"}},
            {"match": {"inLanguage.keyword": "eng"}},
            {"bool": {
              "must_not": {"exists": { "field": "inLanguage"}}
            }}
          ]
        }
      },{
        "regexp": {"datePublished": "20[01][0-9]"}
      },{
        "bool": {
          "minimum_should_match": 1,
          "should": [
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/AR 17550"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/AR 24300"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/AR 27000"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/AR 277"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/AR 27800"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/CW 7000"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/MS 5950"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/PN 63"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/PN 64"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/PN 65"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/PN 66"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/PN 67"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/QH 462"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/QH 463"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/QQ 93"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/QR 8"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/WK 1850"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/XE 55"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZH 6800"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZH 6820"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZH 6830"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZH 9348"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 64"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 65"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 66"}},
            {"match": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 6700"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 6720"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZI 6730"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZK 4600"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO"}},
            {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZQ 9940"}}
          ]
        }
      }],
      "must_not": [{
        "terms": {
          "genre.Text.keyword": [
            "!826484824!",
            "978-3-8375-0470-5",
            "Adressbuch",
            "Altertumskunde",
            "Altkarte",
            "Anleitung",
            "Anthologie",
            "Antiquariatskatalog",
            "Atlas",
            "Aufgabensammlung",
            "Aufsatzsammlung",
            "Aufsatzsammlung[Formschlagwort]",
            "Auktionskatalog",
            "Ausstellung",
            "Ausstellungskatalog",
            "Autobiografie",
            "Beispielsammlung",
            "Bestimmungsbuch",
            "Bibliografie",
            "Bildband",
            "Bilderbuch",
            "Biografie",
            "Biographie",
            "Blu-Ray-Disc",
            "Briefsammlung",
            "Cartoon",
            "CD",
            "CD-ROM",
            "Checkliste",
            "Civil",
            "Comic",
            "Datenbank",
            "Datensammlung",
            "Diagramm",
            "DVD-Audio",
            "DVD-ROM",
            "DVD-Video",
            "Einführung",
            "Erlebnisbericht",
            "Fabel",
            "Fachkunde",
            "Fahrplan",
            "Fallsammlung",
            "Fallstudiensammlung",
            "Festschrift",
            "Fiktionale Darstellung",
            "FiktionaleDarstellung",
            "Film",
            "Filmografie",
            "Formelsammlung",
            "Formularsammlung",
            "Fotografie",
            "Führer",
            "Genealogische Tafel",
            "Gespräch",
            "Hörbuch",
            "Humoristische Darstellung",
            "HumoristischeDarstellung",
            "Inventar",
            "Jugendbuch",
            "Jugendsachbuch",
            "Kalender",
            "Karte",
            "Katalog",
            "Kinderbuch",
            "Kindersachbuch",
            "Kochbuch",
            "Kommentar",
            "Kunstführer",
            "Künstlerbuch",
            "Laudatio",
            "Lehrbuch",
            "Lehrerhandbuch",
            "Lehrmittel",
            "Lehrplan",
            "Liederbuch",
            "Literaturbericht",
            "Loseblattsammlung",
            "Malbuch",
            "Mehrsprachiges Wörterbuch",
            "MehrsprachigesWörterbuch",
            "MonografischeReihe",
            "Nachruf",
            "Norm",
            "Partitur",
            "Plakat",
            "Praktikum",
            "Programmheft",
            "Quelle",
            "Ratgeber",
            "Rede",
            "Regest",
            "Reisebericht",
            "Reportagensammlung",
            "resebericht",
            "Rezension",
            "Sachbilderbuch",
            "Schulbuch",
            "Software",
            "Tabelle",
            "Tafel",
            "Tagebuch",
            "Übungssammlung",
            "Umfrage",
            "Unterrichtseinheit",
            "USB-Stick",
            "Verkaufskatalog",
            "Verzeichnis",
            "Website",
            "Werkverzeichnis",
            "Wörterbuch",
            "Zeitschrift",
            "Zeittafel",
            "Zeitung",
            "Zitatensammlung"
          ]
        }
      },{
       "terms": {
         "isPartOf.keyword": [
            "Strassenbahn-Magazin",
            "Oldtimer-Markt",
            "Straßenbahn-Magazin, Nahverkehr",
            "Lok-Magazin",
            "Eisenbahn-Kurier",
            "Motor-Klassik",
            "Motorrad Classic",
            "Verkehrsgeschichtliche Blätter",
            "Austro-Classic",
            "Eisenbahn-Geschichte",
            "Der Knochenschüttler",
            "Eisenbahn-Journal",
            "Modelleisenbahner",
            "Historischer Kraftverkehr",
            "AufgeHorcht",
            "Deutsches Schiffahrtsarchiv",
            "Die Museums-Eisenbahn",
            "Miba",
            "Achse, Rad und Wagen",
            "Deutsches Technikmuseum Berlin",
            "Fahrrad & Moped",
            "Flieger-Revue",
            "Schienenverkehr aktuell",
            "Flug-Revue",
            "Last & Kraft",
            "Super-Trabi",
            "Leipziger Blätter",
            "Das Archiv",
            "Der Preß'-Kurier",
            "Dampfbahn-Magazin",
            "Die Fähre",
            "Industriekultur",
            "Kultur & Technik",
            "Oldtimer-Praxis",
            "Sächsische Heimatblätter",
            "Technikgeschichte",
            "Elbhang-Kurier",
            "Die Bimmel",
            "Sachsenbummel",
            "Traditionsbahn-Depesche",
            "Das Pross'ner Heft",
            "Schifffahrt am Bodensee",
            "Binnenschifffahrt",
            "Eisenbahn Österreich",
            "Chemnitzer Roland",
            "Jahrbuch für Wirtschaftsgeschichte",
            "Dresdner neueste Nachrichten",
            "Erzgebirgische Heimatblätter <Marienberg>",
            "Oberlausitzer Hausbuch",
            "Sachsenlandkurier",
            "Wirtschaft + Markt",
            "Industriearchäologie",
            "Mercedes-Benz Classic",
            "Stadt + Grün",
            "Bahn extra",
            "Berichte zur Denkmalpflege in Niedersachsen",
            "Garten + Landschaft",
            "Kreuzer",
            "Sächsische Verwaltungsblätter",
            "Straßen von der Frühgeschichte bis in die Moderne",
            "Südhang",
            "Bauwelt",
            "Beiträge zur Rheinkunde",
            "Jahrbuch für Eisenbahngeschichte",
            "Strassen- und Verkehrswesen im hohen und späten Mittelalter",
            "Der Heimatbote",
            "Deutsche Schiffahrt",
            "Flugzeug",
            "Landkalenderbuch für die Sächsische Schweiz und das Osterzgebirge ...",
            "MIBA spezial",
            "Modell-Werft",
            "Reichenbacher Kalender",
            "Sächsische Zeitung / Dresden",
            "Blätter für Technikgeschichte",
            "Die Gartenkunst",
            "Die Zweite Industrielle Revolution",
            "In Fahrt - Autos aus Sachsen",
            "Neue Wege",
            "Verkehrssicherheitsarbeit",
            "Vor Ort",
            "Vorschau & Rückblick",
            "AFZ, der Wald",
            "Denkmalpflege im Rheinland",
            "Denkmalpflege in Baden-Württemberg",
            "Dresdener Beiträge zur Geschichte der Technikwissenschaften",
            "Ferrum",
            "Historikus Vogtland",
            "Jahrbuch Traktoren",
            "Lastauto, Omnibus",
            "Maschinen im Modellbau",
            "Regionalverkehr",
            "Technology and culture",
            "Top Speed",
            "Werkbahnreport",
            "Zeunert's Schmalspurbahnen",
            "Argos",
            "Bahn-Profil",
            "Damals",
            "Denkmalpflege & Kulturgeschichte",
            "Deutsches Architektenblatt / Ausgabe Ost",
            "Dresdner Geschichtsbuch",
            "Einbaum, Lastensegler, Dampfschiff",
            "Hansische Geschichtsblätter",
            "Heimatblatt aus Frohburg, dem Kohrener Land und Umgebung",
            "Im Dienste der historischen Landeskunde",
            "Internationale Seilbahn-Rundschau",
            "Jahrbuch für Eilenburg und Umgebung ...",
            "Landschaftsarchitektur",
            "Oberlausitzer Heimatblätter",
            "Österreichische Ingenieur- und Architekten-Zeitschrift",
            "Räume - Wege - Verkehr",
            "Schiff & Zeit",
            "Stahlbau",
            "Zeitschrift für Unternehmensgeschichte",
            "Bremisches Jahrbuch",
            "Christophorus <Stuttgart> / Deutsche Ausgabe",
            "Das Vogtland-Jahrbuch",
            "Dessauer Kalender",
            "Deutsche Briefmarken-Zeitung, Sammler-Express",
            "Die Fahrschule",
            "Die Glocke / Sonderausgabe",
            "Glückauf",
            "Historische Gärten",
            "Jenaer Jahrbuch zur Technik- und Industriegeschichte",
            "Lokrundschau",
            "Märkisches Jahrbuch für Geschichte",
            "Neugersdorf",
            "P. M.",
            "Parthen-Post für Borsdorf, Zweenfurth, Panitzsch, Cunnersdorf",
            "Planung, Bauausführung und Ertüchtigung von Massivbrücken",
            "Restauro",
            "Sax",
            "Siegerland",
            "Stadtstreicher",
            "Traffix plus",
            "Triangel <Leipzig>",
            "Vogtländische Heimatblätter",
            "Volkswagen-Magazin",
            "Wirtschaftsjournal",
            "Wissenschaft und Technik als Motoren unternehmerischen Handelns",
            "Altlastensanierung als Beitrag zur Minderung des Flächenverbrauchs",
            "Antike Welt",
            "Auto, Motor und Sport",
            "150 Jahre \"Sachsendreier\"",
            "50 Jahre Internationale Seilbahn-Rundschau",
            "75 Jahre Auto Union",
            "Aktuelle Fragen der Stadtbaumplanung, -pflege und -verwendung",
            "Archäologie in Deutschland",
            "Archäologie in Deutschland / Sonderheft",
            "Christophorus-Porsche-Magazin",
            "Circa 1903",
            "Denkmalpflege in Sachsen",
            "Der Spiegel <Hamburg>",
            "Die Elbe",
            "Edition Fahrzeug-Chronik",
            "Einbaum, Lastensegler, Dampfschiff : frühe Schifffahrt in Südwestdeutschland / zsgest. von Ralph Röber",
            "Eisenbahn-Kurier / Special",
            "Bahn-Report",
            "Geschichte der Konsumgesellschaft",
            "Gohlis-Forum",
            "Hamburger Nahverkehrs-Nachrichten",
            "Hamburgs Geschichte einmal anders",
            "Landschaftsprisma ...",
            "Mot",
            "Museumsjournal",
            "Neue Hoyerswerdaer Geschichtshefte",
            "Oberlausitzer Kulturschau",
            "Orangerien - Von fürstlichem Vermögen und gärtnerischer Kunst",
            "Planet Aerospace / Deutsche Ausgabe",
            "Radeberger Blätter zur Stadtgeschichte",
            "Raumplanung",
            "Rheinische Heimatpflege",
            "Schönere Heimat",
            "Strassen- und Verkehrsgeschichte deutscher Städte nach 1945",
            "Technische Denkmale in Sachsen",
            "Traffix",
            "Verkehrs-Rundschau",
            "Augenblicke zwischen Gestern und Morgen",
            "Beiträge zur Agrargeographie und Landwirtschaftsgeschichte des historischen Mitteldeutschlands",
            "Aerospace / Deutsche Ausgabe",
            "Archaeo",
            "Chemnitzer Roland / Beiheft",
            "Curiositas",
            "Czorneboh-Bieleboh-Zeitung",
            "Der Bär von Berlin",
            "Der Holznagel",
            "Der Niederrhein",
            "Der Sorbenturm",
            "Detail / Deutsche Ausgabe",
            "Deutschland Archiv ...",
            "Die Denkmalpflege",
            "Döbelner Mosaik",
            "Drobs",
            "Erkennen - Bewahren - Gestalten",
            "Europe en mouvement",
            "Art <Hamburg>",
            "Aschberger Land",
            "Flug Bahnen",
            "Focus <München>",
            "Frosch-Post Cotta",
            "Führerschule, Thingplatz, \"Judenhaus\"",
            "Garten - Park - Landschaft",
            "Gescheiterte Innovationen",
            "Geschichte - Unternehmen - Archive",
            "Geschichte und Zukunft der deutschen Automobilindustrie",
            "Görlitz",
            "Görlitzer Magazin",
            "Hamburger Blätter für alle Freunde der Eisenbahn",
            "Hebezeuge, Fördermittel",
            "Heimatkalender für die Großenhainer Pflege",
            "Hochland-Kurier",
            "Jahrbuch des Bahnwesens Nah- und Fernverkehr",
            "Jahrbuch für das Erzgebirge ...",
            "Jahrbuch Stadterneuerung",
            "Kamenz",
            "Kanu-News",
            "Kesselsdorfer Heimatkunde",
            "Kippe",
            "Klassiker der Luftfahrt",
            "Klotzscher Heideblatt",
            "Mitteilungen des Freiberger Altertumsvereins",
            "Mitteilungen für sächsische Säugetierfreunde",
            "Mittelalterarchäologie und Bauhandwerk",
            "Modell-Auto-Zeitschrift",
            "Modell-Fan",
            "Monumente",
            "Museum aktuell",
            "Naturschutz und Landschaftsplanung",
            "Naturschutzarbeit in Sachsen",
            "Neikirnger Heimatbote",
            "Neue Landschaft",
            "Oberlausitzer Familien-Kalenderbuch",
            "Oberlausitzer Rundschau",
            "Pfälzer Heimat",
            "Photo deal",
            "Pirnaer Hefte",
            "Postgeschichtliche Vorträge",
            "Restaurator im Handwerk",
            "Richtiger Umgang mit Abfällen",
            "Richtungslampe",
            "Sachsendreier",
            "Sächsische floristische Mitteilungen",
            "Sächsisches Archivblatt",
            "Signal",
            "Spektrum der Wissenschaft",
            "Technik, Arbeit und Umwelt in der Geschichte",
            "Technikland Oberösterreich",
            "The intelligence",
            "Top magazin",
            "Unternehmen im regionalen und lokalen Raum",
            "Via Dresden",
            "Volkskunde in Sachsen",
            "Wiener Geschichtsblätter",
            "Wirtschaft",
            "Wirtschaft, Innovation, Bildung",
            "Wirtschafts- und Wissenschaftsstandort Dresden",
            "WissenD",
            "Zeitschrift für Archäologie des Mittelalters",
            "Zeitschrift für Volkskunde",
            "Zeitschrift für württembergische Landesgeschichte",
            "Zur Entstehung und Frühgeschichte der Stadt Chemnitz",
            "Zwischen Großer Röder und Kleiner Spree",
            "Zwischen Plan und Pleite",
            "Zwischen Wesenitz und Löbauer Wasser",
            "Archiv für Sozialgeschichte",
            "Autorennsport in der DDR",
            "Bahn-Epoche",
            "Bahnhöfe : Geschichten von Ankunft und Abschied / ausgew. von Mario Leis",
            "BahnProfil / Special-Edition",
            "Bauaufgaben des 20. Jahrhunderts",
            "Bauen in Boden und Fels : 3. Kolloquium 22. und 23. Januar 2002 / [3. Kolloquium Bauen in Boden und Fels]. Hrsg.: Hermann Schad. Technische Akademie Esslingen",
            "Bauernhäuser und Bauernhöfe in Sachsen",
            "Bauernzeitung / Wochenblatt für Sachsen",
            "Bautenschutz + Bausanierung",
            "Bautzener Hausbuch 2002",
            "Bayerisches Jahrbuch für Volkskunde",
            "Beiträge zum Naturschutz im Oberen Elbtal / Osterzgebirge",
            "Beiträge zur Agrargeschichte Mitteldeutschlands",
            "Bergknappe",
            "Bergstadt-Nachrichten",
            "Berichte des Instituts für Mechanik und Flächentragwerke ; 4",
            "Berliner Zeitung <Berlin> / Berliner Ausgabe",
            "Bibliotheksjournal der Christian-Weise-Bibliothek Zittau",
            "Bindereport",
            "Blätter für deutsche Landesgeschichte",
            "Blätter für Heimatkunde",
            "Blickpunkt Straßenbahn",
            "2000 Jahre Schifffahrt auf der Mosel",
            "77er-Info",
            "Adel im Wandel",
            "Alemannisches Jahrbuch",
            "Alleen in Deutschland",
            "Alles fließt",
            "Anzeiger des Germanischen Nationalmuseums",
            "Arbeits- und Forschungsberichte zur sächsischen Bodendenkmalpflege",
            "Arbeitsblätter für Restauratoren",
            "Archäologie aktuell im Freistaat Sachsen",
            "Archäologisches Nachrichtenblatt",
            "Archithese",
            "Vom Turm geschaut",
            "Vom Umgang mit Landschaftserscheinungen in der Landschaftsplanung",
            "Von innovativer Krantechnik bis virtual reality: 16. Internationale Kranfachtagung 2008 ; Begleitband zur Kranfachtagung am 18. April 2008 in Magdeburg",
            "Waldstraßenviertel",
            "Wasser & Boden",
            "Weiterbauen am Denkmal",
            "Weltkulturerbe - VIA REGIA",
            "Weltkunst <Hamburg>",
            "Werk, Bauen + Wohnen / Deutsche Ausgabe",
            "Wirtschaft im Wandel",
            "Wirtschaftsgeographische Studien",
            "Wirtschaftswoche <Düsseldorf>",
            "Wissen und Gewissen",
            "Wolkser Wasserturmbote",
            "Zeitschrift des Vereins für Hessische Geschichte und Landeskunde",
            "Zeitschrift für Agrargeschichte und Agrarsoziologie",
            "Zeitschrift für die Geschichte der Saargegend",
            "Zeitschrift für Eisenbahnwesen und Verkehrstechnik",
            "Zeitschrift für schweizerische Archäologie und Kunstgeschichte",
            "Zittauer Geschichtsblätter",
            "Zwischen Wunschtraum und Wirklichkeit?",
            "Boletus",
            "Bonner Geschichtsblätter",
            "Brand eins / Neuland",
            "Brandenburgische Denkmalpflege",
            "Bremsenhandbuch",
            "Bühnentechnische Rundschau",
            "Capital <Hamburg> / Immobilien-Kompass",
            "Cartographica Helvetica",
            "Chemnitzer Seiten",
            "Chronikblätter zur Geschichte von Eibau, Neueibau und Walddorf",
            "DAM-Jahrbuch",
            "Das Dampfmodell",
            "Das Ende der Zuversicht?",
            "Das Hoftor",
            "Das mechanische Musikinstrument",
            "Das neue Deutschland",
            "Das süße Herz Deutschlands",
            "Das Vogtland",
            "De architect / Detail",
            "Delitzscher Heimatkalender",
            "Denkmale der Technik und Industrie im Land Brandenburg",
            "Der Anschnitt",
            "Der Deutschunterricht",
            "Der Kasemattengeist",
            "Der Landkreis",
            "Der mittelsächsische Heimatbote",
            "Deutsche Bauzeitung <Leinfelden-Echterdingen>",
            "Deutsches Architektur-Jahrbuch",
            "Deutsches Architektur-Jahrbuch ...",
            "Die alte Stadt",
            "Die Berücksichtigung der Landschaftsgestaltqualitäten in der Landschaftsplanung, in Umweltverträglichkeitsstudien und in Landschaftspflegerischen Begleitplänen",
            "Die demographische Herausforderung - Sachsens Zukunft gestalten",
            "Die neue Botenfrau",
            "Die Neustadt",
            "Die Ortenau",
            "Die Römer zwischen Alpen und Nordmeer",
            "Die Stadt als Kommunikationsraum",
            "Die Wohnungswirtschaft",
            "Dresdner Heimatgeschichte(n)",
            "Dresdner Mitteilungen",
            "Dresdner Morgenpost",
            "Dresdner Neumarkt-Kurier",
            "Dynamik im Handel",
            "Ein anderes Europa",
            "Eisenbahn-Kurier / DR-Ausgabe",
            "Eisenbahn-Magazin",
            "Element + Bau",
            "Entomologische Nachrichten und Berichte",
            "Entwicklungen in der Bodenmechanik, Bodendynamik und Geotechnik",
            "Ethnographisch-archäologische Zeitschrift",
            "Europäisierung im Alltag",
            "Gärtnerpost",
            "Geographie und Schule",
            "Germania",
            "Ginkgoblätter",
            "Gothaisches Museums-Jahrbuch",
            "Göttinger Jahrbuch",
            "Grenzen & Differenzen",
            "Handel, Transport und Verkehr in Grenzregionen",
            "Hannoversche Geschichtsblätter",
            "Heimatkalender für den Altkreis Bad Liebenwerda, das Mückenberger Ländchen, Ortrand am Schraden und Uebigau-Falkenberg",
            "Heimatkalender für den Landkreis Verden",
            "Heimatland",
            "Helbok, Klaudia; 500 Jahre Frachtführer. 1936. - Das Weissbuch. 1975",
            "Hildesheimer Jahrbuch für Stadt und Stift Hildesheim",
            "Historia in Museo",
            "Ottagono",
            "Ottendorfer Bote",
            "Paper history",
            "Pilot und Flugzeug",
            "Süddeutsche Zeitung <München> / Deutschland-Ausgabe / F1",
            "TAB",
            "Technik zwischen artes und arts",
            "Technikgeschichte des Bodensee-Raumes",
            "Technikgestaltung zwischen Wunsch und Wirklichkeit",
            "Technikvermittlung und Technikpopularisierung",
            "Historic gardens today",
            "Historische Bürowelt",
            "Historische Gärten heute",
            "Historische Gärten heute : zum 80. Geburtstag von Professor Dr. Dieter Hennebo / hrsg. von Michael Rohde ...",
            "History and technology",
            "Holzwege",
            "Homo faber ludens",
            "Horch und Guck",
            "Hub zur Kunst",
            "Hundert sächsische Köpfe",
            "Industriekultur, Stadtentwicklung, soziale Milieus",
            "Pioniere aus Technik und Wirtschaft in Heidelberg",
            "Planungsprozesse - Innovation & Nachhaltigkeit : Tagungsband, Institutskolloquium 2011 am 21. Januar 2011 in Dresden",
            "Post- und Telekommunikationsgeschichte",
            "Prähistorische Zeitschrift",
            "Projektemacher",
            "Radreport",
            "Ratschlag",
            "Rozwój regionalny",
            "Rundbrief Fotografie",
            "Teuringen",
            "Topos",
            "Eutritzscher Rundblick",
            "Festschrift 150 Jahre Gradmessung in Sachsen",
            "Festschrift anlässlich des 10. Jahrestages der Gründung des ZAFT e.V.",
            "Finanz-Spiegel",
            "Finden und Verstehen",
            "Fließende Gewässer als Kulturdenkmale",
            "Forum Ware",
            "Fotogeschichte",
            "Franken unter einem Dach",
            "Freie Presse <Chemnitz> / Chemnitzer Zeitung",
            "Funkamateur",
            "Instrument - Experiment",
            "Jahrbuch",
            "Jahrbuch Bautechnik",
            "Jahrbuch der rheinischen Denkmalpflege",
            "Jahrbuch der staatlichen Schlösser, Burgen und Gärten in Sachsen",
            "Jahrbuch für brandenburgische Landesgeschichte",
            "Jahrbuch für solothurnische Geschichte",
            "Jahrbuch Lokomotiven",
            "Jahrbuch Schienenverkehr",
            "Kalkuliertes Risiko",
            "Keramos",
            "Kleine Betriebe - angepaßte Technologie?",
            "Kölner Domblatt",
            "Kommunalpolitische Blätter <Berlin>",
            "Konstruierte Sichtbarkeiten",
            "Konsum und politische Kommunikation",
            "Korrespondenzblatt",
            "Krafthand",
            "Kunststoff",
            "Landeskundliche Vierteljahrsblätter",
            "Landschaftsgärten in Deutschland",
            "Landtagskurier",
            "Lausitzer Almanach",
            "Leben am See",
            "Leben in Elbgebieten",
            "Leipzig, Mitteldeutschland und Europa",
            "Leipziger Jahrbuch zur Buchgeschichte",
            "Leipziger Kalender",
            "Leipziger Stadtgeschichte",
            "Löbauer Journal",
            "Logistik für Unternehmen",
            "Lok-Report",
            "Lübeckische Blätter",
            "Mainfränkisches Jahrbuch für Geschichte und Kunst",
            "Mainz",
            "Maß und Gewicht / Jahresband",
            "MehrWert",
            "Mensch - Natur - Technik : Dokumentation des Vortragszyklus 24.8. - 12.10.2000 ; Wilhelmshavener Tage, Nr. 8 / [Hrsg.: Nordwestdeutsche Universitätsgesellschaft e. V.]",
            "Menschen unterwegs",
            "Metro magazine",
            "Mitteilungen des Chemnitzer Geschichtsvereins",
            "Mitteilungen des Vereins für Geschichte der Prignitz",
            "Mitteilungen des Vereins für Geschichte der Stadt Nürnberg. - 93 (2006)",
            "Mitteilungen für Hellerau",
            "Mobilität im Wandel - historische, technische und soziale Aspekte",
            "Montan- und Industriegeschichte",
            "Motorrad <Stuttgart>",
            "Mühlhäuser Beiträge",
            "Museumskurier",
            "Natur und Landschaft",
            "Natur und Mensch",
            "Naturwissenschaftliche Rundschau",
            "Neue Mobilität in der Region Stuttgart",
            "Neue Tarifmodelle im Öffentlichen Personennahverkehr : Workshop ; 3. November 2004 in Kassel ; [Verbundworkshop für die deutschen Bundesländer] / Veranst.: Deutsche Verkehrswissenschaftliche Gesellschaft e.V. Leitung: Manfred Ritschel",
            "Neuland gewinnen",
            "Neumarkt-Kurier",
            "Nonstop",
            "NTM",
            "Oberbayerisches Archiv",
            "Offa",
            "Offenland - Sachsens Vogelwelt und Landwirtschaft",
            "Österreichische Zeitschrift für Geschichtswissenschaften",
            "Saarbrücken in Fahrt",
            "Sächsischer SHK-Handwerkskalender",
            "Sächsische-Schweiz-Initiative",
            "Sanitär- + Heizungstechnik",
            "Säugetierkundliche Informationen",
            "Schiene",
            "Schiff und Hafen, Kommandobrücke",
            "Schmalspurbahnen : Reiseführer Deutschland ; Geschichte , Strecken, Fahrzeuge, Termine / [Red.: André Marks ...]",
            "Schriftenreihe des Dresdner Instituts für Verkehr und Umwelt ; [5]",
            "Schwäbische Heimat",
            "Schweizerische Zeitschrift für Geschichte",
            "Seniorenfreundliche Kommune",
            "Signal + Draht",
            "Silesia nova",
            "Smartismus",
            "Stadtbauwelt",
            "StadtBlick",
            "Stadtgeschichte",
            "Stern",
            "Strukturfonds aktuell",
            "Top-Speed.info",
            "Torgauer Heimatkalender",
            "Tourismus und Industriekultur",
            "Touristik-Report",
            "Tunnel",
            "Umrisse",
            "Umwelt-Geschichte",
            "Unternehmensgeschichte heute: Theorieangebote, Quellen, Forschungstrends",
            "Unterwegs und mobil"
          ]
        }
      },{
       "terms": {
         "publisher.name.keyword": [
            "publisher.name",
            "Motorbuch-Verl.",
            "GeraMond",
            "Delius Klasing",
            "Heel",
            "EK-Verl.",
            "Podszun",
            "Motorbuch",
            "Sutton",
            "Motorbuch Verl.",
            "Koehler",
            "Ian Allan",
            "Bahnprojekt Stuttgart-Ulm",
            "Komet",
            "Voyageur Press",
            "Amberley",
            "Motorbuch-Verlag",
            "Hauschild",
            "Haynes",
            "Kleine Vennekate",
            "ÖBB-CI & M Werbeagentur",
            "Weltbild",
            "Amberley Publ.",
            "History Press",
            "International Maritime Economic History Association",
            "McFarland",
            "Aktionsbündnis gegen Stuttgart 21",
            "Elbe-Dnjepr-Verl.",
            "Kenning",
            "Endisch",
            "Society of Automotive Engineers",
            "MBI",
            "Schwandl",
            "The History Press",
            "Haufe",
            "Ulmer",
            "GVE",
            "GDL",
            "Motorbooks",
            "ÖBB -CI & M Werbeagentur",
            "Oficyna Wydawnicza Politechniki Warszawskiej",
            "Schrader",
            "SMV",
            "Volkswagen",
            "Aviatic-Verl.",
            "Kohlhammer",
            "Volkswagen AG",
            "EK-Verlag",
            "Neddermeyer",
            "Allan",
            "Bechtermünz",
            "DGEG Medien",
            "NGV",
            "Verkehrsverbund Mittelsachsen",
            "Delius Klasing Verlag, ",
            "Huber",
            "Iconografix",
            "Krafthand-Verl. Schulz",
            "MVV",
            "Steiner",
            "Verkehrsverbund Oberelbe (VVO) Oberelbe Tours",
            "Adam Gordon",
            "Bassermann",
            "Bild u. Heimat",
            "Böhlau",
            "Deutsche Bahn AG, Kommunikation",
            "GeraMond-Verl.",
            "Haynes Publ.",
            "History",
            "Johns Hopkins Univ. Pr.",
            "Johns Hopkins University Press",
            "Krafthand Medien GmbH, ",
            "White-Star-Verl.",
            "[Aktionsbündnis gegen Stuttgart 21]",
            "DIE-Archiv",
            "Dorling Kindersley",
            "Dresdner Verkehrsbetriebe",
            "Irwell Pr.",
            "Klartext",
            "Krafthand",
            "Mittler",
            "Motorbuch Verlag, ",
            "Österr. Kunst- und Kulturverl.",
            "Pietsch",
            "Rabe",
            "Seehafen-Verl.",
            "Shire",
            "SSB",
            "St Petroc InfoPubl.",
            "Ullstein",
            "Veloce Publ.",
            "Verl. Europa-Lehrmittel",
            "Verl. Kraftakt",
            "Wieland",
            "Zeunert",
            "Crowood",
            "DGEG-Medien",
            "Ed. Dörfler im Nebel-Verl.",
            "EK-Verlag, ",
            "Engelsdorfer Verl.",
            "Franzis",
            "GeraMond Verl.",
            "Goldmann",
            "Hampp",
            "Hinstorff",
            "Kosmos",
            "Landwirtschaftsverl.",
            "Middleton Press",
            "Mohr Siebeck",
            "Noodle Books",
            "Pro Business",
            "Salzwasser-Verl.",
            "Tempus",
            "Texas A&M University Press",
            "Thales",
            "TÜV-Verl.",
            "Arcadia Publ.",
            "Aus- und Weiterbildungszentrum Verkehrsgewerbe",
            "Barteld",
            "Bertelsmann",
            "Boorberg, ",
            "Convent",
            "Conway",
            "GeraMond Verlag",
            "Grohmann",
            "Jakab",
            "MBI Publ.",
            "Piper",
            "Resch",
            "Selbstverl. der Fachrichtung Forstwissenschaften der TU Dresden",
            "Tredition",
            "Turmforum Bahnprojekt Stuttgart-Ulm",
            "VBN, Neddermeyer",
            "Verkehrsverbund Oberelbe (VVO)",
            "Wachsenburgverl.",
            "Westermann",
            "[Initiative Leben in Stuttgart - Kein Stuttgart 21]",
            "Amberley Publishing",
            "AS-Verl.",
            "Aurum",
            "Bernard und Graefe",
            "BMW Mobile Tradition",
            "Böttger",
            "Bucheli",
            "Crowood Press",
            "Detlefsen",
            "Ed. Maritim",
            "EK-Vlg",
            "Fonthill Media",
            "Gordon",
            "Handwerk und Technik",
            "Hochparterre",
            "Ian Allan Publishing",
            "Koehlers",
            "Lightmoor Press, ",
            "Lorenz",
            "Mann",
            "Matador",
            "Motor Presse Stuttgart",
            "Motorbooks International",
            "MZA Verlag, ",
            "Nara-Verl.",
            "Norton",
            "Pro MESSAGE",
            "Pro-Bahn-Verl. und Reisen",
            "Rockstuhl",
            "Rosenberg",
            "Schwarzkopf & Schwarzkopf",
            "Shire Publ.",
            "Silver Link Publ.",
            "Stenlake Publ.",
            "Stuttgarter Straßenbahnen AG",
            "Veloce",
            "Verkehrsverbund Vogtland",
            "Wild Swan Publ.",
            "Zweckverband ÖPNV Vogtland",
            "Zweckverband Verkehrsverbund Oberlausitz-Niederschlesien",
            "A. Gordon",
            "ArGe Drehscheibe",
            "AS Verl.",
            "Convent-Verl.",
            "GeraMond Verlag, ",
            "History pr.",
            "Interessenverband der Zittauer Schmalspurbahnen e.V.",
            "Kellner",
            "Koch",
            "Koehlers V.-G.",
            "Koehlers Verlagsges.",
            "Motorbuch Verlag",
            "Neckar-Verl.",
            "Simon & Schuster",
            "VBN Verl. Neddermeyer",
            "Verkehrsverbund Oberelbe",
            "Voyageur",
            "Air-Britain",
            "AirDOC",
            "Conway Maritime",
            "Eisenbahnmuseum",
            "Elbe-Spree-Verl.",
            "Electa",
            "GeraNova-Zeitschr.-Verl.",
            "Hollinek",
            "Ian Allan Publishing, ",
            "Initiative Leben in Stuttgart - Kein Stuttgart 21",
            "Klasing",
            "Klein",
            "McFarland & Co",
            "Robert Schwandl Verlag, ",
            "Sutton-Verl.",
            "Tosa",
            "VBN Verlag B. Neddermeyer, ",
            "Verkehrsverbund Oberlausitz-Niederschlesien",
            "Verl. Europa-Lehrmittel Nourney, Vollmer",
            "Voyageur Press, ",
            "Zweckverband für den Nahverkehrsraum",
            "Agentur ERZ.art",
            "Agrar- und Freilichtmuseum Schloß Blankenhain",
            "Air Britain Historians",
            "Allan Publ.",
            "Amberley Publishing, ",
            "Amberley, ",
            "Arcadia Publishing, ",
            "Archaeopress",
            "Arndt",
            "Ballantine Books",
            "Barthels",
            "Canada Science and Technology Museum",
            "Canal Book Shop",
            "DGEG Medien, ",
            "Endisch, D",
            "engelmann-pictures",
            "Fahrrad-Veteranen-Freunde-Dresden 1990 e.V.",
            "Förderverein Hapag-Halle",
            "Fraktion Bündnis 90/Die Grünen im Sächsischen Landtag, ",
            "GeraMond Verlag GmbH, ",
            "Haufe Gruppe, ",
            "Haynes Publishing, ",
            "Heel, ",
            "HEEL-Verl.",
            "History Press Ireland",
            "Ian Allan Publ.",
            "IG Bürger für Stuttgart 21",
            "Internat. Maritime Economic History Assoc.",
            "Klartext-Verl.",
            "Koehler-Mittler",
            "Koehlers Verl. - Ges.",
            "Koehlers Verl.-Ges.",
            "Koehlers Verlagsgesellschaft, ",
            "Krafthand-Medien",
            "McFarland & Co  Inc.",
            "Mohr Siebeck, ",
            "Motorbuchverl.",
            "MZA-Verl.",
            "ÖBB",
            "ÖBB-Infrastruktur Bau",
            "Podszun, ",
            "Rudolf Haufe Verlag",
            "Schweers + Wall",
            "Science Museum",
            "Scottish Postal History Society",
            "Sutton Verlag GmbH, ",
            "Technisches Museum",
            "The History Press, ",
            "tredition, ",
            "TurmForum Stuttgart 21",
            "TUSA-Natursteine",
            "TUSA-Natursteine GmbH",
            "Verein Sächsischer Eisenbahnfreunde",
            "Verein zur Förderung des Lauenburger Elbschiffahrtsmuseums",
            "Verkehrsmuseum",
            "Verkehrsverbund Mittelsachsen GmbH, ",
            "Verkehrsverbund Oberelbe (VVO), Oberelbe Tours",
            "Verl. Europa-Lehrmittel, Nourney, Vollmer",
            "Verl. Podszun-Motorbücher",
            "\"Belarus\"",
            "[Heel]",
            "[Kleingartenverein \"Rosenaue\" e.V.]",
            "[Kleingärtnerverein Johannistal 1832 e.V.]",
            "[Langzaam Verkeer]",
            "[Sundwerbung]",
            "Airlife",
            "Airlife, ",
            "Altonaer Museum",
            "Arbeitskreis Schiffahrtsmuseum",
            "Arcadia Publishing (SC)",
            "August Horch Museum",
            "August Horch Museum Zwickau",
            "August-Horch-Museum",
            "Automobile Museum",
            "Automuseum Carl Benz",
            "Bahnprojekt Stuttgart-Ulm e.V.",
            "Bahnprojekt Stuttgart-Ulm e.V., Kommunikationsbüro",
            "BahnTV",
            "Berlin : Militärhistorisches Museum der Bundeswehr - Flugplatz Berlin-Gatow, ",
            "Berlin Story Verl.",
            "Bernhard & Graefe",
            "Bernisches Historisches Museum [u.a.]",
            "Bertelsmann, W",
            "Berufsbildungswerk d. Spedition in Hessen",
            "Berufsgenossenschaft für Gesundheitsdienst und Wohlfahrtspflege",
            "Bild und Heimat Verl.",
            "Bodensteiner",
            "Bodensteiner Verl.",
            "Bouvier",
            "Bündnis 90, Die Grünen, Bundestagsfraktion",
            "Bündnis 90/Die Grünen",
            "Bündnis 90/Die Grünen Fraktion im Sächsischen Landtag, ",
            "Bündnis 90/Die Grünen, Fraktion im Sächsischen Landtag",
            "Bürgerbahn statt Börsenbahn u.a.",
            "Bürgerschaft Kupferdreh, AK Heimtakunde und Archiv",
            "Columbia Univ. Pr.",
            "Convent Verl.",
            "Conway Bloomsbury",
            "Conway, ",
            "Crowood Pr.",
            "Crucible Books",
            "DB Museum",
            "Delius & Klasing",
            "Delius Klasing Verl.",
            "Delius Klasing, ",
            "Delius-Klasing-Verl.",
            "Deutsches Bergbau-Museum",
            "Dornie Publ.",
            "Dresdner Verkehrsbetriebe AG",
            "Dt. Meeresmuseum",
            "Dt. Museum",
            "Dt. Museums-Eisenbahn",
            "Dt. Technikmuseum",
            "EK-Verlag GmbH, ",
            "Elbe-Spree-Verlag",
            "ERZ.art",
            "ERZ.art Agentur für Werbung & Event, ",
            "Erzgebirgsmuseum [u.a.]",
            "Falc-Transfer Publ. House",
            "For Dummies a Wiley Brand",
            "Förderkreis Museum Spandau",
            "Förderverein HapagHalle Cuxhaven",
            "Förderverein LLN c/o TU Berlin",
            "Franz Steiner Verlag, ",
            "Franzis, ",
            "Freilichtmuseum des Bezirks Oberbayern",
            "Freunde des Lotsenschoners No 5 Elbe",
            "Freundes- und Förderkreis des Instituts für mobile Maschinen und Nutzfahrzeuge",
            "Friends of the National Railway Museum",
            "GeraMond [u.a.]",
            "GeraMond, ",
            "Haufe Lexware, ",
            "Haufe Mediengruppe",
            "Haufe Verlag",
            "Haufe Verlag, ",
            "Haufe-Lexware",
            "Haufe-Lexware GmbH & Co. KG",
            "Haufe-Mediengruppe",
            "Hauschild, H M",
            "Haynes [u.a.]",
            "Haynes Publishing",
            "Haynes Publishing Group",
            "Helms",
            "Helms-Museum",
            "History Press, ",
            "Hoboken Historical Museum",
            "Hohenloher Freilandmuseum",
            "IG Luftfahrtgeschichte",
            "IG Preßnitztalbahn",
            "Industriemuseum",
            "Inselfreunde Usedom [u.a.]",
            "Interessengemeinschaft Dampflokomotive 58 3047 e.V., Freizeitgruppe der Stiftung Bahn-Sozialwerk",
            "Interessengemeinschaft Historische Fernmeldetechnik e.V., ",
            "Interessengemeinschaft Luftschiffhafen",
            "Interessengemeinschaft Weißeritztalbahn",
            "Interessenverband der Zittauer Schmalspurbahnen",
            "Internat. Economic History Assoc.",
            "International Maritime Economic History Assocociation",
            "Isle of Man Postal History Society",
            "Kerchensteiner",
            "KIS",
            "Klartext, ",
            "Klartext-Verlag, ",
            "Kleingartenverein \"Hoffnung - West\"",
            "Kleingartenverein Am Friederikenschacht",
            "Kleingartenverein Brose",
            "Kleingartenverein Knautkleeberg 069 e.V.",
            "Kleingartenverein Leutzscher Aue e.V.",
            "Kleingartenverein Tunnelwiese e.V.",
            "Kleingartenverein Volkshain Anger",
            "Koehler & Amelang",
            "Koehler & Amelang [u.a.]",
            "Koehler, ",
            "Koehlers Verl.-Ges. mbH",
            "Koehlers Verlagsgesellschaft [u.a.]",
            "Komet Verlag GmbH, ",
            "Komet-Verlag",
            "Krafthand Medien, ",
            "Krafthand Verl.",
            "Krafthand Verl., W. Schulz",
            "Krafthand Verlag Walter Schulz",
            "Landesamt für Archäologie mit Landesmuseum für Vorgeschichte",
            "Lebanese British Friends of the National Museum",
            "Lippisches Landesmuseum",
            "Mariners' Museum",
            "MBI Pub.",
            "MBI Publ. Co.",
            "MBI Publishing Company",
            "McFarland & Co.",
            "McFarland & Co.,  Inc.",
            "Motorbuch, ",
            "Motorbuch-Verl",
            "Motorbuch-Verl., ",
            "Motorbuch-Verlag, ",
            "Motoretta-Verl.",
            "Motor-Presse",
            "Motor-Presse-Verl.",
            "Museum der Westlausitz Kamenz",
            "Museumshafen Oevelgönne",
            "NASA Office of External Relations, NASA History Office",
            "National Aeronautics and Space Administration, Office of Communications, Public Outreach Division, NASA History Program Office",
            "National Railway Museum [u.a.]",
            "Naturfreundejugend Deutschlands",
            "ÖBB-CI&M Werbeagentur",
            "Pietsch-Verlag",
            "Piffy Publishing",
            "PIN",
            "Podszum",
            "Podzun-Pallas",
            "Pro Leipzig",
            "Prokopp & Hechensteiner",
            "Resch, ",
            "Rosenberg Publ.",
            "Rosenberg Publishing",
            "Rosenheimer",
            "Rosenheimer Verlagshaus",
            "Rudolf Haufe Verlag GmbH & Co. KG",
            "Sächsische Landesstelle für Museumswesen",
            "Schwandl Verl.",
            "Schwandl, Robert",
            "Schwarzkopf und Schwarzkopf",
            "Shire Publications Ltd",
            "Silver Link Publishing",
            "Simon & Schuster, ",
            "Smithsonian National Air and Space Museum [u.a.]",
            "Society of Automotive Engineers, Inc.",
            "SPD-Bundestagsfraktion",
            "SSB AG",
            "SSB AG, Pressestelle",
            "SSB, ",
            "SSBMedien",
            "SSI Schäfer, Fritz-Schäfer-GmbH, Fabriken für Lager-, Betriebs-, Büroeinrichtungen, Abfalltechnik und Recycling",
            "Staatliche Schlösser, Burgen und Gärten Sachsen",
            "Steiner, ",
            "Steirische Verl.-Ges., ",
            "Stenlake Pub",
            "Stenlake Publishing",
            "Straßenbahnfreunde Mainz e. V.",
            "Straßenbahnmuseum Dresden e.V.",
            "Stuttgarter Straßenbahnen AG, Pressestelle",
            "Sutton [u.a.]",
            "Sutton Publishing Ltd, ",
            "Sutton Verl.",
            "Sutton Verlag, ",
            "Sutton Zeitreise, ",
            "Techn. Museum",
            "Technisches Museum Wien",
            "Thales]",
            "The History Press Ltd, ",
            "The Viking Ship Museum [u.a.]",
            "tredition GmbH, ",
            "Ulmer [u.a.]",
            "Ulmer, ",
            "VBN Verlag Bernd Neddermeyer",
            "VBN, ",
            "VBN, Verl. Bernd Neddermeyer",
            "Veloce Enterprises",
            "Veloce Press",
            "Veloce Publishing",
            "Veloce Publishing Ltd",
            "Verein Freiberger Briefmarkenfreunde [u.a.]",
            "Verein für die Geschichte der Stadt Bacharach und der Viertäler",
            "Verein für Wirtschaftshistorische Studien",
            "Verein Tram-Museum Zürich",
            "Verein Verkehrsamateure und Museumsbahn",
            "Vereinigte Motor-Verl.",
            "Vereinigte Schiffervereine von Alsleben und Umgebung Undine",
            "Verkehrsmuseum Dresden",
            "Verkehrsverbund Oberelbe (VVO) GmbH, Oberelbe Tours",
            "Verl. des Rheinischen Vereins f. Denkmalpflege u. Landschaftsschutz",
            "Verl. des Römisch-Germanischen Zentralmuseums",
            "Verl. Die Fähre",
            "Verl. Die Hanse",
            "Verl. Die Werkstatt",
            "Verl. Europa-Lehrmittel Nourney, Vollmer GmbH & Co. KG, ",
            "Verlag ACE Auto-Club Europa e.V.",
            "Verlag Podszun-Motorbücher GmbH, ",
            "Vestisches Museum",
            "Vitra-Design-Museum",
            "Volkswagen Aktienges.",
            "Volkswagen Handelsmarketing",
            "Vorstand der Stiftung Dt. Segelflugmuseum mit Modellflug",
            "Vorstand Verein der Kleingärtner Gartenfreunde Leipzig Südost",
            "Voyageur  Press",
            "Voyageur Press.",
            "Wachsenburgverlag",
            "Wells Local History Group",
            "Westermann, ",
            "Westfälisches Industriemuseum",
            "WIMAD, Förderverein für Wissenschaftler, Ingenieure und Marketing Dresden",
            "Zeitgeist Media",
            "Zeitgut-Verl.",
            "Zeppelin-Museum",
            "Zweckverband Bevorzugtes Erholungsgebiet Altenautal",
            "Zweckverband ÖPNV"
          ]
        }
      },
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/CW 7400"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/CW 7500"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/DG 9500"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/MX"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/MY"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/MZ"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 2052"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 2150"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 2152"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 22"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 23"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 24"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 25"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 26"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 3050"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 3901"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 4050"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 505"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 506"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 507"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 508"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 509"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 55"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 6020"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 7050"}},
       {"prefix": {"about.@id.keyword": "https://rvk.uni-regensburg.de/api/json/ancestors/ZO 8050"}}
      ]
    }
  }
}
        else:
             searchbody=None
                                                                                                    
        for record in esgenerator(host=args.host,port=9200,index=args.index,id=args.id,type=args.type,body=searchbody,source=True,source_exclude=None,source_include=None,headless=True):
            recstrlen=len(json.dumps(record,indent=None))
            #print(json.dumps(record,indent=tabbing),"\n")
            #length=len(json.dumps(record,indent=None))
            newrecord=enrich_record(record,None,args.host,str(args.port),map)
            if args.index!="resources" and newrecord and len(json.dumps(newrecord,indent=None))>recstrlen:
                print(json.dumps(newrecord))
            elif args.index=="resources" and (newrecord.get("author") or newrecord.get("contributor")):
                print(json.dumps(newrecord))
            else:
                continue
            
